"""Built-in objective checks."""

from reprocheck.checks.findings import (
    RC001_NO_README,
    RC002_NO_PYTHON_VERSION,
    RC003_NO_PYTHON_CONFIG,
    RC004_NOT_A_GIT_REPOSITORY,
    RC005_DIRTY_WORKING_TREE,
    RC006_NO_TESTS,
    RC007_NO_CI_WORKFLOWS,
    RC008_NO_GITIGNORE,
    RC009_MULTIPLE_PACKAGE_MANAGERS,
    RC010_NO_PYTHON_FILES,
    run_checks,
)

__all__ = [
    "RC001_NO_README",
    "RC002_NO_PYTHON_VERSION",
    "RC003_NO_PYTHON_CONFIG",
    "RC004_NOT_A_GIT_REPOSITORY",
    "RC005_DIRTY_WORKING_TREE",
    "RC006_NO_TESTS",
    "RC007_NO_CI_WORKFLOWS",
    "RC008_NO_GITIGNORE",
    "RC009_MULTIPLE_PACKAGE_MANAGERS",
    "RC010_NO_PYTHON_FILES",
    "run_checks",
]
