"""Check for generated artifacts that are not ignored (RC140).

A pattern is only required when there is objective evidence that the project
uses the tool that generates it, so no universal list is imposed.
"""

from __future__ import annotations

from reprocheck.facts import Facts
from reprocheck.models import Confidence, Finding, Severity

RC140_ARTIFACTS_NOT_IGNORED = "RC140"

# Evidence required per ignore pattern.
#   "python"   - the project contains Python source files
#   "build"    - the project builds a distribution
#   "venv"     - the project pins or documents a virtual environment
#   <tool>     - the tool was detected in use
PATTERN_EVIDENCE: dict[str, tuple[str, ...]] = {
    "__pycache__/": ("python",),
    "build/": ("build",),
    "dist/": ("build",),
    "*.egg-info/": ("build",),
    ".venv/": ("venv",),
    "venv/": ("venv",),
    ".pytest_cache/": ("pytest",),
    ".ruff_cache/": ("ruff",),
    ".mypy_cache/": ("mypy",),
    ".tox/": ("tox",),
    ".nox/": ("nox",),
}


def missing_artifact_patterns(facts: Facts) -> tuple[str, ...]:
    """Ignore patterns the detected tools require and the file does not cover.

    Shared with the suggestion engine, so a proposal can only ever contain a
    pattern the check itself proved is missing.
    """
    if not facts.gitignore.exists:
        return ()
    return tuple(
        sorted(
            pattern
            for pattern, requirements in PATTERN_EVIDENCE.items()
            if not facts.gitignore.ignores(pattern)
            and _has_evidence(facts, requirements)
        )
    )


def check_gitignore_artifacts(facts: Facts) -> list[Finding]:
    """Report generated artifacts that the root ``.gitignore`` does not cover."""
    missing = missing_artifact_patterns(facts)
    if not missing:
        return []

    return [
        Finding(
            id=RC140_ARTIFACTS_NOT_IGNORED,
            title="Common generated artifacts are not ignored",
            severity=Severity.WARNING,
            category="vcs",
            message=(
                "The root .gitignore does not cover "
                + ", ".join(missing)
                + ", which are generated by tools or steps detected in this "
                "project."
            ),
            evidence=".gitignore",
            file=".gitignore",
            confidence=Confidence.HIGH,
        )
    ]


def _has_evidence(facts: Facts, requirements: tuple[str, ...]) -> bool:
    return all(_requirement_met(facts, item) for item in requirements)


def _requirement_met(facts: Facts, requirement: str) -> bool:
    if requirement == "python":
        return facts.project.python_file_count > 0
    if requirement == "build":
        return facts.has_file("pyproject.toml") or facts.has_file("setup.py")
    if requirement == "venv":
        return (
            facts.has_file(".python-version")
            or facts.has_directory(".venv")
            or facts.has_directory("venv")
            or any(signal.name == "conda" for signal in facts.tools)
            or _documents_virtualenv(facts)
        )
    return any(signal.name == requirement for signal in facts.tools)


def _documents_virtualenv(facts: Facts) -> bool:
    return any(
        "venv" in item.command or "virtualenv" in item.command
        for item in facts.readme_commands
    )
